import { Book, Category } from "@/types/book.types";

export const NAV_LINKS = [
  { name: "Home", path: "/" },
  { name: "Books", path: "/books" },
  { name: "About", path: "/about" },
  { name: "Support", path: "/support" },
];

export const BOOKS_DATA: Book[] = [
  {
    id: 1,
    title: "Clean Code",
    titleBn: "ক্লিন কোড: চটপট ও গুছানো কোডিং",
    author: "Robert C. Martin",
    category: "Programming",
    categoryBn: "প্রোগ্রামিং",
    rating: 4.8,
    reviews: 120,
    copiesAvailable: 5,
    badge: "Best Seller",
    coverImage: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: 2,
    title: "The Pragmatic Programmer",
    titleBn: "দ্যা প্রাগম্যাটিক প্রোগ্রামার",
    author: "Andrew Hunt & David Thomas",
    category: "Software Eng.",
    categoryBn: "সফটওয়্যার ইঞ্জিনিয়ারিং",
    rating: 4.9,
    reviews: 98,
    copiesAvailable: 3,
    badge: "Trending",
    coverImage: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: 3,
    title: "Introduction to Algorithms",
    titleBn: "অ্যালগরিদম পরিচিতি ও অ্যানালাইসিস",
    author: "Thomas H. Cormen",
    category: "Computer Science",
    categoryBn: "কম্পিউটার সায়েন্স",
    rating: 4.7,
    reviews: 145,
    copiesAvailable: 2,
    badge: "Academic",
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: 4,
    title: "Eloquent JavaScript",
    titleBn: "ইলোকোয়েন্ট জাভাস্ক্রিপ্ট",
    author: "Marijn Haverbeke",
    category: "Web Dev",
    categoryBn: "ওয়েব ডেভেলপমেন্ট",
    rating: 4.9,
    reviews: 210,
    copiesAvailable: 8,
    badge: "Popular",
    coverImage: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: 5,
    title: "Design Patterns",
    titleBn: "ডিজাইন প্যাটার্নস: অবজেক্ট ওরিয়েন্টেড",
    author: "Erich Gamma & Gang of Four",
    category: "Software Eng.",
    categoryBn: "সফটওয়্যার ইঞ্জিনিয়ারিং",
    rating: 4.6,
    reviews: 75,
    copiesAvailable: 4,
    badge: "Essential",
    coverImage: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: 6,
    title: "Grokking Algorithms",
    titleBn: "গ্রোকিং অ্যালগরিদম চিত্রসহ",
    author: "Aditya Y. Bhargava",
    category: "Programming",
    categoryBn: "প্রোগ্রামিং",
    rating: 4.9,
    reviews: 180,
    copiesAvailable: 6,
    badge: "Recommended",
    coverImage: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=600",
  },
];

export const CATEGORIES_DATA: Category[] = [
  { name: "All", nameBn: "সকল ক্যাটাগরি" },
  { name: "Programming", nameBn: "প্রোগ্রামিং" },
  { name: "Software Eng.", nameBn: "সফটওয়্যার ইঞ্জিনিয়ারিং" },
  { name: "Computer Science", nameBn: "কম্পিউটার সায়েন্স" },
  { name: "Web Dev", nameBn: "ওয়েব ডেভেলপমেন্ট" },
];
